# custom
language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - "pypy"  # PyPy2 2.5.0
    - "pypy3" # Pypy3 2.4.0
    - "pypy-5.3.1" 

install:
    - pip install -U setuptools==33.1.1 coveralls coverage
    - python bootstrap.py
    - bin/buildout

script:
    - coverage run bin/test -v1
after_success:
    - coverage combine
    - coveralls

notifications:
    email: false

cache:
  pip: true
  directories:
    - eggs/
