# custom
language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - "3.7-dev"  # A 3.7 build is not available yet
    - "pypy2.7"
    - "pypy3.5"

install:
    - pip install -U setuptools==33.1.1 coverage
    - python bootstrap.py
    - bin/buildout

script:
    - coverage run bin/test -v1

notifications:
    email: false

cache:
  pip: true
  directories:
    - eggs/
